name: 'Export MermaidJS erdiagrams from database'
description: 'Exports MermaidJS entity relationship diagrams from existing databases'
inputs:
  output:
    description: 'output file'
    required: false
    default: erdiagram.svg
  config:
    description: 'path to Mermerd config file'
    required: true
  connectionString:
    description: 'connectionString'
    required: true
runs:
  using: "composite"
  env: 
    MERMERD_VERSION: "0.7.0"
    MERMERD_TAR: "mermerd_${{ MERMERD_VERSION }}_linux_amd64.tar.gz"
  steps:
    - uses: actions/checkout@v3
    - name: Download Mermerd binary
      shell: bash
      run: wget -c https://github.com/KarnerTh/mermerd/releases/download/v${{ MERMERD_VERSION }}/${{ MERMERD_TAR }}
    - name: Extract Mermerd
      shell: bash
      run: tar -xf ${{ MERMERD_TAR }}
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.15.0
    - name: Install mermaid-cli
      shell: bash
      run: npm install -g @mermaid-js/mermaid-cli
    - name: Generate Mermaid ER diagram
      shell: bash
      run: ./mermerd --runConfig ${{ inputs.config }} -c ${{ inputs.connectionString }} -o erdiagram.mmd
    - name: Convert .mmd to .svg
      shell: bash
      run: mmdc -i erdiagram.mmd -o ${{ inputs.output }}
